name: PR Validation

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - .vscode/**
      - "*.md"
      - LICENSE

concurrency:
  group: ${{ format('pr-{0}', github.event.pull_request.number) }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        run: |
          corepack enable
          corepack prepare --activate
          yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint
